ResearchCollectionsAndPreservation/docker

- settingfiles/my.cnf
> Added my.cnf file.

- etl/RecapDataLoad.ktr
Updated the etl transformation file to give db connection as parameter.
> Updated the etl transformation file to give db connection as parameter.

- jenkins/Dockerfile
update the file with maven and git installation
> update the file with maven and git installation

- jenkins/Dockerfile
> Git plugin

- jenkins/Dockerfile
> Gradle and SSH Pluging

- jenkins/Dockerfile
- mysql/Dockerfile
- scsb-solr-server/Dockerfile
Modifed jenkins docker to get latest version, added ENTRYPOINT for solr and mysql
> modifed jenkins docker to get latest version, added ENTRYPOINT for solr and mysql

- scsb-solr-client/Dockerfile
Added entrypoint for scsb-solr-client
> Added entrypoint for scsb-solr-client

- scsb-solr-server/Dockerfile
> modified the entrypoint

- jenkins/Dockerfile
added java, gradle, junit plugin and cobertura installation
> added java, gradle, junit plugin and cobertura installation

- jenkins/Dockerfile
Added dependant plugins for cobertura
> Added dependant plugins for cobertura

- scsb-solr-server-tst/Dockerfile
Added config for scsb-solr-server-test
> Added config for scsb-solr-server-test

- scsb-solr-client-tst/Dockerfile
Added Dockerfile for scsb-solr-client-tst
> Added Dockerfile for scsb-solr-client-tst

- scsb-etl-tst/Dockerfile
- scsb-persistence-tst/Dockerfile
Added Dockerfile for scsb-etl-tst
> Added Dockerfile for scsb-etl-tst

- scsb-mysql-dev/Dockerfile
- scsb-mysql-dev/startup.sh
- scsb-mysql-tst/Dockerfile
- scsb-mysql-tst/startup.sh
Updated the appropriate folder location for
> Updated the appropriate folder location for

- scsb-mysql-dev/startup.sh
Updated the appropriate folder location
> Updated the appropriate folder location

- scsb-etl-tst/Dockerfile
- scsb-etl/Dockerfile
- scsb-persistence-tst/Dockerfile
- scsb-persistence/Dockerfile
- scsb-solr-client-tst/Dockerfile
- scsb-solr-client/Dockerfile
Added -XX:+HeapDumpOnOutOfMemoryError for the applications
> Added -XX:+HeapDumpOnOutOfMemoryError for the applications

- scsb-persistence/Dockerfile
- scsb-solr-client/Dockerfile
> Added -Denvironment

- scsb/Dockerfile
Added docker file for scsb project
> Added docker file for scsb project

- scsb-activemq/Dockerfile
Added docker file for activemq
> Added docker file for activemq

- scsb-circ/shellBuild.sh
- scsb-etl/shellBuild.sh
- scsb-persistence/shellBuild.sh
- scsb-solr-client/shellBuild.sh
- scsb-solr-server/shellBuild.sh
- scsb/shellBuild.sh
> fixed the checkout tag issue

- scsb-circ/shellBuild.sh
- scsb-etl/shellBuild.sh
- scsb-persistence/shellBuild.sh
- scsb-solr-client/shellBuild.sh
- scsb-solr-server/shellBuild.sh
- scsb/shellBuild.sh
update the shell script to pull the latest when tag is not given
> update the shell script to pull the latest when tag is not given

- scsb-shiro/Dockerfile
- scsb-shiro/shellBuild.sh
- scsb-ui/Dockerfile
- scsb-ui/shellBuild.sh
Added docker files for scsb-ui and scsb-shiro
> Added docker files for scsb-ui and scsb-shiro

- scsb-activemq/Dockerfile
- scsb-activemq/config.sh
- scsb-activemq/env-container
> Fixed the jmx url issue

- scsb-mysql/12_PERMISSIONS_T.sql
Modified permission name 'Create Users'  to  'Create User' in permission_t
> Modified permission name 'Create Users'  to  'Create User' in permission_t

- jenkins/Dockerfile
- scsb-activemq-base/Dockerfile
- scsb-activemq/Dockerfile
- scsb-base/Dockerfile
- scsb-cas/Dockerfile
- scsb-circ/Dockerfile
- scsb-etl/Dockerfile
- scsb-mysql/Dockerfile
- scsb-persistence/Dockerfile
- scsb-shiro/Dockerfile
- scsb-solr-base/Dockerfile
- scsb-solr-client/Dockerfile
- scsb-solr-server/Dockerfile
- scsb-solr-server/managed-schema
- scsb-solr-server/shellBuild.sh
- scsb-solr-server/solrconfig.xml
- scsb-ui/Dockerfile
- scsb/Dockerfile
Modified for following,
1. RECAP-646 : Modified the Dockerfile to use the 'recapscsb' base images
2. RECAP-647 : Upgraded the Solr version to 6.5.0
> Modified docker and Upgraded Solr

- scsb-solr-server/solrconfig.xml
Added commitwithin parameter in solr config
> Added commitwithin parameter in solr config

- scsb-activemq/activemq.xml
Increased the max framesize to 400mb in activemq
> Increased the max framesize to 400mb in activemq

- scsb-mysql/Dockerfile
- scsb-mysql/my.cnf
- scsb-mysql/startup.sh
RECAP-676 : Fixed the issue with timezone. Modified to set timezone to 'America/New_York'
> RECAP-676 : Fixed the issue with timezone. Modified to set timezone to 'America/New_York'

- scsb-mysql/10_RECAP_ALTER_SCRIPTS.sql
RECAP-827 : Added script to alter script sql file.
> RECAP-827 : Added script to alter script sql file.
